version: '3.3'
services:
  web:
    image: "hotel-reservation:latest"
    ports:
      - "8081:8080"
    depends_on:
      - hk-mongodb
    links:
      - hk-mongodb
    environment:
      host: http://192.168.99.100
  hk-mongodb:
    container_name: hk-mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet