AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Reservation API
Resources:
  ReservationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.techpro.api.hotelreservation.lambda.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/hotel-reservation-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootSampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: ReservationApi
